### ISSUE TITLE
Typo in pivotal.full-name variable gives error message "Unable to mark feature as started"

### ISSUE THREAD

**Issue by matellis** [trydionel/git-pivotal#13]
If you set pivotal.full-name variable in github to something that doesn't exactly match what you entered in Pivotal Tracker you get the error message "Unable to mark feature as started".

Not sure if you can do anything about this but it would be helpful if the utility gave a more descriptive error message.

**Comment by Capncavedan** [comment]
Also found this message would result when feature did not have number of points assigned in Tracker

**Comment by trydionel** [comment]
farnsworth_v("Good news everyone!")

I've been looking around for ways to manage this, thinking that the PivotalTracker gem swallowed all errors whole. I've just found that they push the server errors through to the client though, so I can indeed start giving better error messages. I'll add this story to the upcoming milestone. Thanks for your patience!

Jeff

**Comment by trydionel** [comment]
Available in v0.8.1.
