### ISSUE TITLE
RFE: a config option to take the default branch names without asking for them on each git {feature,bug,chore}

### ISSUE THREAD

**Issue by sboss** [trydionel/git-pivotal#19]
RFE: a config option to take the default branch names without asking for them on each git {feature,bug,chore}.  Automatically take the generated defaults.

This again is a nice to have not a must to have.

PS> this is awesome! thanks for the ruby gem.

**Comment by trydionel** [comment]
Hey Scott,

Good news -- this feature already exists! You can use the `-D` option ("defaults") to enter no-interaction mode, or the `-q` option to silence all output and interaction. Check out the help for more options (`--help`).

Jeff

**Comment by sboss** [comment]
Thanks. I must have missed it.

On Mon, May 2, 2011 at 7:43 PM, trydionel
reply@reply.github.com
wrote:
