### ISSUE TITLE
branch upstream binding

### ISSUE THREAD

**Issue by a-b** [trydionel/git-pivotal#22]
Hello,
in some reason when I create new branch with git-pivotal it is not connected to any upstream.
So I should use $ gitb --set-upstream 12345-new-branch-name origin/HEAD
Can we automate this procedure?

**Comment by trydionel** [comment]
Hey a-b,

I'm not sure I understand the issue you're having. You want to set the newly-created feature branch to track origin/HEAD? What benefit does that afford you?

Jeff

**Comment by a-b** [comment]
Hello,

sure, I want to set the newly-created feature branch to track origin/master

**Comment by trydionel** [comment]
Could you elaborate a bit more? This seems like an uncommon workflow, and I'd like to know more of your reasoning behind wanting to add it to Git Pivotal.
