### ISSUE TITLE
Rest client version mismatch

### ISSUE THREAD

**Issue by tombh** [trydionel/git-pivotal#23]
I'm so excited to get this working! But I'm getting this error when I try to run any of the commands;

`/usr/lib/ruby/1.8/rubygems.rb:779:in `report_activate_error': RubyGem version error: rest-client(1.6.1 not ~> 1.4.0) (Gem::LoadError)`

I'm trying this on Debian Squeeze and I've never done anything with Ruby ever before.

Thanks :)

**Comment by trydionel** [comment]
Hey tombh,

Are you using the latest version of Git Pivotal (v0.8.0)? Updating to the latest might solve your trouble.

If that doesn't work, you could try uninstalling and re-installing rest-client:

```
[sudo] gem uninstall rest-client
[sudo] gem install rest-client
```

Jeff

**Comment by tombh** [comment]
Thanks for the reply. Yes, I'm using version 0.8.0 and I tried reinstalling the rest-client gem as you suggested, but still I get the error :( Here it is in full;

``` bash
/usr/lib/ruby/1.8/rubygems.rb:779:in `report_activate_error': RubyGem version error: rest-client(1.6.1 not ~> 1.4.0) (Gem::LoadError)
        from /usr/lib/ruby/1.8/rubygems.rb:214:in `activate'
        from /usr/lib/ruby/1.8/rubygems.rb:1082:in `gem'
        from ./../lib/pivotal/base.rb:2
        from ./../lib/pivotal.rb:5:in `require'
        from ./../lib/pivotal.rb:5
        from ./git-bug:5:in `require'
        from ./git-bug:5
```

**Comment by trydionel** [comment]
Hey tombh,

The backtrace you listed is pointing to files removed in a previous version (https://github.com/trydionel/git-pivotal/commit/41a6962655ba84207f3f8b4b960c9236cec79122). Can you confirm again that you've got version 0.8.0 of the git-pivotal gem installed? Try uninstalling and re-installing git-pivotal -- that might resolve your issues.

**Comment by tombh** [comment]
You were absolutely right. Although I had the correct version I did a `git log` and saw that the commits were different, then I looked at `git remote -v` and realised that I was using webagogos fork of git-pivotal.

You're version installed first time without a hitch. Happy now :)
