### ISSUE TITLE
Including commands in porcelain

### ISSUE THREAD

**Issue by tombh** [trydionel/git-pivotal#24]
Sorry, another quick question. I'm on Debian and after installing the gem the various git commands are not available in the porcelain. Should the installation make the commands available or is the user responsible for this?

I've tried copying the contents of the bin/ folder to all git-core/ but then I get errors saying that files from the `commands` folder cannot be found.

Thanks.

**Comment by trydionel** [comment]
Hey tombh,

I'm afraid I can't offer too much advice here, as I don't run Debian (and don't know what porcelain is at all!), but I can offer this -- all you need to do is ensure your gem binaries directory is included in `$PATH`. You can find out where this is on your system by inspecting `gem env` for the `EXECUTABLE DIRECTORY`. No copying of files required.

Jeff

**Comment by tombh** [comment]
Thanks for taking the time to help me Jeff.

Yep, it was just that the gem path was not in my `$PATH`. Finally got it working now :)

Though I think I might have found a bug - Full names with a hyphen in (eg Thomas Buckley-Houston) seem to never have any stories associated with them. When I changed my name to not include a hyphen it then found all the stories assigned to me. Should I file this as a separate issue?

Thanks again Jeff,
tom

**Comment by trydionel** [comment]
Hey tombh,

Happy to help! Glad it's working as expected for you. Regarding the hyphen issue, yes, please open a separate ticket for that. Thanks!

Jeff
