### ISSUE TITLE
422 status

### ISSUE THREAD

**Issue by komba** [trydionel/git-pivotal#25]
When I trying run git feature I got error:

Retrieving latest features from Pivotal Tracker...
Story: Landing page
URL:   http://www.pivotaltracker.com/story/show/13xxxxxx
Updating feature status in Pivotal Tracker...
/home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/rest-client-1.6.3/lib/restclient/abstract_response.rb:48:in `return!': 422 Unprocessable Entity (RestClient::UnprocessableEntity)
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/rest-client-1.6.3/lib/restclient/request.rb:228:in`process_result'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/rest-client-1.6.3/lib/restclient/request.rb:176:in `transmit'
    from /home/komba/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:543:in`start'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/rest-client-1.6.3/lib/restclient/request.rb:170:in `transmit'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/rest-client-1.6.3/lib/restclient/request.rb:64:in`execute'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/rest-client-1.6.3/lib/restclient/request.rb:33:in `execute'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/rest-client-1.6.3/lib/restclient/resource.rb:80:in`put'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/pivotal-tracker-0.3.1/lib/pivotal-tracker/story.rb:65:in `update'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/git-pivotal-0.8.0/bin/../lib/commands/pick.rb:37:in`run!'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/gems/git-pivotal-0.8.0/bin/git-feature:7
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/bin/git-feature:19:in `load'
    from /home/komba/.rvm/gems/ree-1.8.7-2011.03@pivotal_test/bin/git-feature:19

**Comment by trydionel** [comment]
Hey komba,

Are you still seeing this behavior? It seems like just a temporary issue (perhaps Pivotal Tracker was down at the time, or sent an invalid response), and I can't reproduce it locally.

Jeff

**Comment by komba** [comment]
Just tried to run "git feature" - and I've this error again

**Comment by trydionel** [comment]
Well that's peculiar. Do you have SSL enabled on your project perhaps? Git-Pivotal currently lacks the ability to support projects with SSL enabled (I believe there's a ticket open on this).

**Comment by komba** [comment]
No, SSL disabled. With SSL enabled I got 400 error 'Bad request'.
I just created new project and got the same error..

**Comment by trydionel** [comment]
A bit of digging through Pivotal Tracker's support turns up this article: http://community.pivotaltracker.com/pivotal/topics/error_422_on_the_story_api. It suggests that the problem might be coming from a configuration issue. Double-check your git-pivotal settings (stored in .git/config or ~/.gitconfig), especially your "Full Name".

If that doesn't turn up anything, you could try building the gem from my `develop` branch. It has some better error reporting than v0.8.0.

Please report back with your findings!

**Comment by komba** [comment]
Oh man, 24 days. Really,in .git/config full name must be specified . It works now. Many thanks for you)
