### ISSUE TITLE
Commands is not a module

### ISSUE THREAD

**Issue by kalabiyau** [trydionel/git-pivotal#27]
gemfile 
  Using git-pivotal (0.8.0) from git://github.com/trydionel/git-pivotal.git (at v0.8.0) 

produces

Commands is not a module
/home/**_/.bundler/ruby/1.9.1/git-pivotal-77914a3fc324/lib/commands/base.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in`require'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in`block in load_dependency'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in`load_dependency'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
/home/**_/.bundler/ruby/1.9.1/git-pivotal-77914a3fc324/lib/git-pivotal.rb:3:in `<top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in`require'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in`each'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in `block in require'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in`each'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in `require'
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler.rb:120:in`require'

**Comment by trydionel** [comment]
Hey kalabiyau,

It looks like you're trying to install git-pivotal through Bundler by specifying the Github source. I recommend you install it by simply `gem install git-pivotal`.
