### ISSUE TITLE
git chore

### ISSUE THREAD

**Issue by pauldruziak** [trydionel/git-pivotal#3]
git: 'chore' is not a git-command. See 'git --help'.

**Comment by trydionel** [comment]
Oops!  Looks like I need to update the documentation -- "This command has been left as an exercise for the reader".

Thanks for posting the issue. I'll update the gem shortly.

**Comment by trydionel** [comment]
Fixed in v0.2.2!

**Comment by pauldruziak** [comment]
great work, thanks
