### ISSUE TITLE
Add a command to switch between stories

### ISSUE THREAD

**Issue by kar** [trydionel/git-pivotal#31]
It'd be nice to be able to switch between stories - when you are doing one story, and you didn't finish it yet but want to immediately start another important story, and after finishing the latter one, get back to the old one.

**Comment by trydionel** [comment]
You can do this already! git-pivotal simply creates git branches to track your stories, so all of the typical git techniques still apply.

```
# from your in-progress 1234-my-original-story branch...
$ git checkout master
$ git feature
# git-pivotal output...
# complete the new story...
$ git finish
$ git checkout 1234-my-original-story
```

Jeff

**Comment by kar** [comment]
Ahh, right, as simple as that :D Great! Thank you
