### ISSUE TITLE
Incompatible with ruby 1.8.7

### ISSUE THREAD

**Issue by TriKro** [trydionel/git-pivotal#34]
Ran into an issue running with ruby 1.8.7 will try and patch:

```
Updating feature status in Pivotal Tracker...
/Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/git-pivotal-0.2.2/bin/../lib/pivotal/base.rb:29: warning: multiple values for a block parameter (3 for 1)
    from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/request.rb:226
```

/Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/git-pivotal-0.2.2/bin/../lib/pivotal/base.rb:30:in `update_attributes': undefined method`code' for #Array:0x105d01aa0 (NoMethodError)
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/request.rb:226:in `call'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/request.rb:226:in`process_result'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/request.rb:176:in `transmit'
        from /Users/tristankromer/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:543:in`start'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/request.rb:170:in `transmit'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/request.rb:64:in`execute'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/request.rb:33:in `execute'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/rest-client-1.6.3/lib/restclient/resource.rb:80:in`put'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/git-pivotal-0.2.2/bin/../lib/pivotal/base.rb:29:in `update_attributes'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/git-pivotal-0.2.2/bin/../lib/pivotal/story.rb:11:in`start!'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/git-pivotal-0.2.2/bin/../lib/commands/pick.rb:36:in `run!'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/gems/git-pivotal-0.2.2/bin/git-feature:8
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/bin/git-feature:19:in`load'
        from /Users/tristankromer/.rvm/gems/ruby-1.8.7-p352@joke-off/bin/git-feature:19

**Comment by trydionel** [comment]
Hey TriKro,

It appears that you're running an old version of git-pivotal. Please upgrade to the latest (v0.8.2) -- I've just verified that the tests pass under 1.8.7. Please let me know if you see any issues!

Jeff

**Comment by TriKro** [comment]
Thanks, it seems that without specifying 0.8.2 bundler installs 0.2.2, I can only presume due to a nokogiri conflict. Git-pivotal does not seem to play nice with Nokogiri 1.4.7 and instead insists on 1.4.3.1

Are you planning on updating to nokogiri 1.4.7 at any point?

**Comment by trydionel** [comment]
You're installing git-pivotal via Bundler? I hadn't imagined that use case, and instead expected it to be installed as a vanilla Ruby gem, especially considering that git-pivotal expects a user-global configuration file. What advantage does using Bundler provide in this case?

Regarding the version conflicts: I don't directly rely on Nokogiri -- that bubbles up through dependencies. I'll see if any of them can be safely updated.

**Comment by TriKro** [comment]
lol...to be honest, I hadn't even considered using installing it any other way.

I should probably point out that I've taught myself rails over past 8 months so I'm sure I'm giving myself some bad habits. I thought bundler was fairly typical but don't listen to me! :)

I like git-pivotal quite a lot now that I have it running on at least one distributed project.

**Comment by trydionel** [comment]
Ah, well welcome to the Ruby/Rails community then! Don't worry, there are many more bad habits to pick up ;D

So, my recommendation is to install git-pivotal through `gem install`. If you're only using the binaries it provides (`git feature` and the like), you shouldn't have to worry about gem activation errors from attempting to load e.g. two version of Nokogiri. Likewise, Bundler is smart enough to figure out the correct version of Nokogiri to use in your application, so you're safe there too. At the very least, this will clear the version conflict in your Gemfile and let you use any Nokogiri you choose! I'll investigate updating the Pivotal-Tracker gem in the next release to make this a moot point.

Glad to hear you like git-pivotal!

**Comment by TriKro** [comment]
That's working tremendously better. Thanks for the help!
