### ISSUE TITLE
Surnames with hyphens don't work

### ISSUE THREAD

**Issue by tombh** [trydionel/git-pivotal#35]
My name (Thomas Buckley-Houston) isn't recognised. I had to change my name on pivotaltracker.com to remove the hypen to get it to work.

**Comment by trydionel** [comment]
Hey tombh,

Unfortunately, I believe this is an issue with the Pivotal-Tracker gem (my interface to the PT API). I'll explore some to see if I can find a workaround, or if there's an easy patch to send upstream. Thanks!

Jeff

**Comment by tombh** [comment]
Hey Jeff,

I did think there was a good chance that this was caused by something
further upstream.

tom

On 17 August 2011 01:08, trydionel
reply@reply.github.com
wrote:

**Comment by docwhat** [comment]
I suspect it's having a hard time with umlauts as well: "Christian Höltje"
