### ISSUE TITLE
undefined method `body' for #<RestClient::Response:0x2aaaabcd6498> (NoMethodError)

### ISSUE THREAD

**Issue by fs** [trydionel/git-pivotal#4]
~/test/git-pt (master) > git feature
/usr/lib64/ruby/gems/1.8/gems/git-pivotal-0.2.2/bin/../lib/commands/pick.rb:7: warning: parenthesize argument(s) for future version
/usr/lib64/ruby/gems/1.8/gems/git-pivotal-0.2.2/bin/../lib/commands/pick.rb:11: warning: parenthesize argument(s) for future version
/usr/lib64/ruby/gems/1.8/gems/git-pivotal-0.2.2/bin/../lib/commands/pick.rb:15: warning: parenthesize argument(s) for future version
Retrieving latest features from Pivotal Tracker...
/usr/lib64/ruby/gems/1.8/gems/git-pivotal-0.2.2/bin/../lib/pivotal/collection.rb:59:in `all': undefined method`body' for #RestClient::Response:0x2aaaabcd6498 (NoMethodError)
    from /usr/lib64/ruby/gems/1.8/gems/git-pivotal-0.2.2/bin/../lib/pivotal/collection.rb:22:in `find'
    from /usr/lib64/ruby/gems/1.8/gems/git-pivotal-0.2.2/bin/../lib/commands/pick.rb:25:in`run!'
    from /usr/lib64/ruby/gems/1.8/gems/git-pivotal-0.2.2/bin/git-feature:8
    from /usr/bin/git-feature:19:in `load'
    from /usr/bin/git-feature:19

**Comment by trydionel** [comment]
Looks like you're using an older version of rest-client.  Try upgrading to the latest (1.4.2) for an immediate fix.  I'll codify dependency version requirements in a future release.

Thanks for the message!

**Comment by fs** [comment]
Thanks, works for me!
