### ISSUE TITLE
How to specify custom feature/bug/chore?

### ISSUE THREAD

**Issue by fs** [trydionel/git-pivotal#5]
Hey guys,

As I can see we have no way to specify on which feature/bug/chore we want to works.
Currently git feature/bug/chore selects first story from PT.
You know in real work we should split our time between diff stories at the same time: feature, urgent bug fix.

It will be very helpful to add something like get feature STORY_ID functionality.
If you agree I could do this.

Thanks,
Timur

**Comment by trydionel** [comment]
Hey Timur,

Thanks for your input.  I personally would prefer to not implement this feature.  A big objective I have with this project is to enforce a specific workflow, and adding the option to essentially choose your own tickets breaks that notion.  You can accomplish this same end-goal by simply `git feature`-ing a feature, then checking out master again to `git bug` an urgent bugfix (assuming you keep your Pivotal Tracker queue in order according to priority).  There are also complications purely from a technical standpoint (e.g., calling `git bug` with a feature story id) that further reduce my interest in this feature.

I understand how some people would see this useful though, so I'll happily consider any code you produce.  Fork the project and send me a pull request when you've got something interesting (in a topic branch, if possible).

Thanks!
Jeff
