### ISSUE TITLE
Unable to mark Story as finished

### ISSUE THREAD

**Issue by natikgadzhi** [trydionel/git-pivotal#7]
Hi, 

I like the workflow, but.. 
The first story i started using git pivotal, it said that it can't finish the story, 

The story is a chore, all the tasks inside the chore are closed, the chose is mine and it's started. 

As i saw in the code, there's no debug version to see what exactly happened on the API level. 

What could it be?

**Comment by natikgadzhi** [comment]
http://github.com/enspiral/git-pivotal/commit/03cb3780ed021581c1e9d5e799c934bc5b62a536

Here it is. Please, pull this and bump the version.

**Comment by trydionel** [comment]
Resolved in v0.8.0
