### ISSUE TITLE
default branch name wrong for bug/chore

### ISSUE THREAD

**Issue by dzajic** [trydionel/git-pivotal#9]
Output shows default branch will be "bugfix" but it ends up being "feature":

`git bug`

`Retrieving latest bugs from Pivotal Tracker...`

`Story: date of birth - use calendar widget`

`URL:   http://www.pivotaltracker.com/story/show/######`

`Updating bug status in Pivotal Tracker...`

`Enter branch name (will be prepended by ######) [bugfix]:`

`Creating ######-feature branch...`

`Switched to a new branch '######-feature'`

I haven't tried it for a "chore", but I assume the behavior will be the same.

**Comment by trydionel** [comment]
Resolved in v0.8.0
